### ISSUE TITLE
Rendering issue on Intel cards

### ISSUE THREAD

**Issue by lov** [Vidvox/hap-in-avfoundation#1]
On Intel cards the decoding of Hap frames goes wrong, see attached picture.

To fix that need to call **glFlush()**  right after glCompressedTexSubImage2D() in HapPixelBufferTexture setDecodedFrame: method.

BTW, this needs to be added to the _hap-quicktime-playback-demo_ project too.

![hapavfissue](https://cloud.githubusercontent.com/assets/270203/5546800/709dae90-8b4b-11e4-9ac2-1030f25a583c.jpg)

**Comment by bangnoise** [comment]
The flush shouldn't be needed and isn't particularly desirable - the problem looks more like memory being reused too soon

**Comment by lov** [comment]
That is interesting. I always needed  that flush in HapPixelBufferTexture class to make it work on Intel chips (with the QT codec as well). I think we talked about that a couple of years ago.
