### ISSUE TITLE
GIF import not supported anymore

### ISSUE THREAD

**Issue by sonarkon** [Vidvox/hap-in-avfoundation#11]
VVBatchExporter allowed for conversion of gifs to Hap. Any reason why AVF-BatchConverter does not allow GIF import?

**Comment by mrRay** [comment]
the "AVF" in "AVF-BatchConverter" refers to the media framework that it uses  (AVFoundation).  AVFoundation doesn't support GIFs- the other batch exporter you referred to used QuickTime instead of AVFoundation, which *did* support GIFs.
