### ISSUE TITLE
Batch converter doesn't work on still images

### ISSUE THREAD

**Issue by nivekevil** [Vidvox/hap-in-avfoundation#12]
Howdy,

Sorry if I'm doing this incorrectly; I'm new here. The old VVBatchConverter would turn still images (JPEG etc) into Hap files, but I'm unable to import any stills into the AVFBatchConverter. I'm assuming this is intended, but is there any chance that functionality might return?  

Thanks for you help!

**Comment by mrRay** [comment]
nope, sorry- the old batch converter's support for still images came entirely from quicktime (quicktime inherently supported converting still images to and from movies).  this batch converter is based on the AVFoundation framework, which doesn't offer this functionality.
