### ISSUE TITLE
AVF Batch Converter: Crashes while exporting movies to larger dimensions

### ISSUE THREAD

**Issue by kleurbleur** [Vidvox/hap-in-avfoundation#18]
Settings are:
- HAP
- No Audio
- Resize to 1920 x 1080
- Add _HAP suffix
- Export to different folder

Movie is:
- Prores 422
- 1280 x 720 or 1024 x 768

I only tested it with these two files. If the resolution is larger than the 1920 x1080 everything is fine. Looks like sizing up is crashing it. 
[Archive.zip](https://github.com/Vidvox/hap-in-avfoundation/files/1934276/Archive.zip)

**Comment by mrRay** [comment]
thanks for reporting this, i think i was able to fix it- please give this build a try and let me know if you have any further difficulties:

https://github.com/Vidvox/hap-in-avfoundation/releases/tag/1.5.3

**Comment by kleurbleur** [comment]
That fixed it, thanks!
