### ISSUE TITLE
Crash when opening a non-hap Video

### ISSUE THREAD

**Issue by eromanc** [Vidvox/hap-in-avfoundation#3]
Hi. First of all Thanks for all the great work, in this library, Hap has been super helpful to me.

Well, I have an App that plays video, and I'm using Hap In AV Foundation since it came out, it actually works very good, but recently I decided to update to your last version of the library and I started to have a crash when playing non-hap videos, specifically h264 (but I also tried with Photo Jpeg) 

Then I tried the Example you provide "HapInAVF Test App" And the same thing happens.
The line of code (210) is this one:

```objective-c
		HapDecoderFrame			*dxtFrame = [hapOutput allocFrameClosestToTime:[hapOutput itemTimeForMachAbsoluteTime:mach_absolute_time()]];
```

It used to work great, because if you didn't have a Hap Video, that call returned nil, and you could proceed with a normal decoding with regular AVFoundation stuff, but now It crashes there.

Here is a screenshot

![screen shot 2015-10-12 at 6 25 42 pm](https://cloud.githubusercontent.com/assets/1731560/10441474/c848a1fa-710e-11e5-9ad7-db2563314009.png)

Sometimes, the crash is a little bit more specific, and the line where crashes is  in the dispatch_async(decodeQueue....

corresponding to AVPlayerItemHapDXTOutput.m

```objective-c
	if (!foundExactMatchToTarget)	{
		//	now use GCD to start decoding the frame
		dispatch_async(decodeQueue, ^{
			[self _decodeFrameForTime:n];
		});
	}
```

Right now a possible workaround would be to use the codec string to know if you are playing a Hap Video, and if that is the case that call works fine, otherwise proceed with a regular AVFoundation stuff.

However, I liked the other approach better, seemed to me more clean, well, If there is anything I can help, please let me know. and Thank you in Advance.

**Comment by mrRay** [comment]
thanks- i'm closing this issue because 0a0dd0aa1fc7aaaa7125e1e29e585e713311448d should address your problem, please re-open it if it's still an issue!

**Comment by eromanc** [comment]
Thanks. Works perfect again.
