### ISSUE TITLE
Cannot run on OSX 10.11 (see 12-12-2019 commit)

### ISSUE THREAD

**Issue by anome** [Vidvox/hap-in-avfoundation#38]
Hi,

Because OSX 10.11 does not feature os_unfair_lock, HAP decoding crashes.
If I replace this feature by the old OSSpinLock, it works again.

It all started with commit https://github.com/Vidvox/hap-in-avfoundation/commit/4226a51c010e8b37f9c0feaff2752475e0779148 : so a partial revert is the solution.

Should I submit my pull request ? Or the use of os_unfair_lock is a must-have, so OSX 10.11 support should be deprecated ?

Thank you. Philippe

**Comment by mrRay** [comment]
whoops, sorry about that- please let me know if commit 0ff6cae1db6c3b5f0b0aa0b9a2e3f4bedaaf4ee6 doesn't fix this for you!

**Comment by anome** [comment]
Hello @mrRay,
So far so good, it's working fine, thank you.
I looked at the code and it's indeed better than my commit/revert !
