### ISSUE TITLE
Decoding Issue using the Test App since last commit

### ISSUE THREAD

**Issue by yderidde** [Vidvox/hap-in-avfoundation#4]
Since the last commit , the decoding/rendering is not working as expected. It looks like the output is dimmed and if you resize the app, it all go wrong ... 
https://github.com/Vidvox/hap-in-avfoundation/commit/bb2861dfe7ff5bb3b8813e5d959e51b11de8bcda

**Comment by tobiasebsen** [comment]
I have the same issue. Since bb2861dfe7ff5bb3b8813e5d959e51b11de8bcda the output is flickering on Hap1 movies. On Hap 5 it's just all red background. It's a huge commit, so it's really difficult to spot the lines that break the code.

**Comment by mrRay** [comment]
thanks everybody, i'm aware of this and fixed it a few days ago in a branch i've been working on recently.  the problem has nothing to do with decoding, a GL view's just getting an errant glActiveTexture() call!

**Comment by tobiasebsen** [comment]
That's great. When will you push the fixed branch?
