### ISSUE TITLE
[feature] Throw warning when pixel format is not divisible by 4

### ISSUE THREAD

**Issue by VuiMuich** [Vidvox/hap-in-avfoundation#41]
So plenty of HAP decoder implementations like Christie Pandoras Box and Dataton WatchOut are picky about pixel formats that are not divisible by 4.

So if the encoder could throw a warning, when the input file doesn't comply to this spec. 
Right now I don't have a reference where this is actually specified, so I am also unsure, why some decoders are actually failing on this and some don't. But as a fact Pandoras Box throws a criticla render engine error for non-compliant files and wont render. WatchOut I at least complains in an error as well, but I am not sure if it tries to render though.

**Comment by bangnoise** [comment]
I'd suggest you pursue this with the makers of the problem decoders. There is no technical reason to limit resolution to be divisible by four. It's true that the underlying compressed texture formats have a block size of 4x4, but that places no restriction on the dimensions of coded images - for odd-width images, the last block in the row is only partially decoded.
